# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180302_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
